// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MirageQueue.Postgres.Databases;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MirageQueue.Postgres.Databases.Migrations
{
    [DbContext(typeof(MirageQueueDbContext))]
    partial class MirageQueueDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MirageQueue.Messages.Entities.InboundMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MessageContract")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("InboundMessage", "mirage_queue");
                });

            modelBuilder.Entity("MirageQueue.Messages.Entities.OutboundMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConsumerEndpoint")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("ExceptionType")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("InboundMessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessageContract")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ProcessingToken")
                        .HasColumnType("uuid");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .ValueGeneratedOnAddOrUpdate()
                        .IsConcurrencyToken();

                    b.HasKey("Id");

                    b.HasIndex("InboundMessageId");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "CreateAt", "Id");

                    b.HasIndex("Status", "UpdateAt");

                    b.HasIndex("InboundMessageId", "ConsumerEndpoint")
                        .IsUnique();

                    b.ToTable("OutboundMessage", "mirage_queue");
                });

            modelBuilder.Entity("MirageQueue.Messages.Entities.ScheduledInboundMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExecuteAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MessageContract")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Status", "ExecuteAt");

                    b.ToTable("ScheduledInboundMessage", "mirage_queue");
                });

            modelBuilder.Entity("MirageQueue.Messages.Entities.OutboundMessage", b =>
                {
                    b.HasOne("MirageQueue.Messages.Entities.InboundMessage", "InboundMessage")
                        .WithMany()
                        .HasForeignKey("InboundMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InboundMessage");
                });
#pragma warning restore 612, 618
        }
    }
}
